name: Vole
version: "0.6.0"
license: "MPL-2.0"
date: 2025-01-09
description: |
    Vole organises lengthy explorations: Backtrack search in permutation groups with graphs

authors:
    - name: Mun See Chang
      url: mailto:msc2@st-andrews.ac.uk
    - name: Christopher Jefferson
      url: https://heather.cafe
    - name: Wilf A. Wilson
      url: https://wilf.me

maintainers:
    - name: Christopher Jefferson
      url: https://heather.cafe
    - name: Wilf A. Wilson
      url: https://wilf.me

GAP: ">= 4.13.0"

needed-pkgs:
    - name: "Digraphs"
      version: ">= 1.1.1"
      url: "https://digraphs.github.io/Digraphs"
    - name: "IO"
      version: ">= 4.7.0"
      url: "https://gap-packages.github.io/io"
    - name: "json"
      version: ">= 2.0.1"
      url: "https://gap-packages.github.io/json/"
    - name: "datastructures"
      version: ">= 0.2.6"
      url: "https://gap-packages.github.io/datastructures"
    - name: "images"
      version: ">=1.3.0"
      url: "https://gap-packages.github.io/images/"
    - name: "primgrp"
      version: ">=3.4.0"
      url: "https://gap-packages.github.io/primgrp/"

suggested-pkgs:
    - name: "AutoDoc"
      version: ">= 2019.09.04"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "ferret"
      version: ">= 1.0.2"
      url: "https://gap-packages.github.io/ferret/"
    - name: "QuickCheck"
      version: ">= 0.1"
      url: "https://gap-packages.github.io/quickcheck"
    - name: "OrbitalGraphs"
      version: ">= 0.1"
      url: "https://gap-packages.github.io/OrbitalGraphs"

www: https://peal.github.io/vole
readme: README.md
packageinfo: https://peal.github.io/vole/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/peal/vole/releases/download/v0.6.0/vole-0.6.0.tar.gz

abstract: |
    
    <Strong>Vole</Strong> is a <Strong>GAP</Strong> package that implements
    algorithms in finite permutation groups, such as canonical images, stabilisers,
    and subgroup intersection. These are all implemented as part of the general
    'graph backtracking' framework.

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    permutation group, backtrack, search, backtracking, graph, digraph, normaliser, normalizer, stabiliser, stabilizer, group, subgroup, intersection, conjugacy, coset, transporter.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CJW25</span>]   <b class='BibAuthor'>Chang, M. S., Jefferson, C. and Wilson, W. A.</b>,
     <i class='BibTitle'>Vole, Vole organises lengthy explorations: Backtrack search in permutation groups with graphs,
             Version 0.6.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://peal.github.io/vole">https://peal.github.io/vole</a></span>.
    </p>
    

bibtex: |
    @misc{ Vole,
      author =           {Chang, M. S. and Jefferson, C. and Wilson, W. A.},
      title =            {{Vole},    {Vole   organises   lengthy   explorations:
                          Backtrack  search  in permutation groups with graphs},
                          {V}ersion 0.6.0},
      month =            {Jan},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href                    {https://peal.github.io/vole}
                          {\texttt{https://peal.github.io/}\discretionary
                          {}{}{}\texttt{vole}}},
      keywords =         {permutation  group;  backtrack;  search; backtracking;
                          graph;  digraph;  normaliser;  normalizer; stabiliser;
                          stabilizer;  group; subgroup; intersection; conjugacy;
                          coset; transporter},
      printedkey =       {CJW25}
    }

